apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-middleware
  name: mag-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mag-middleware
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mag-middleware
    spec:
      containers:
      - image: mag_middleware
        name: mag-middleware
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
