version: "3"
    
services:
  mag-restaurant:
    image: mag-restaurant
    build: restaurant/.
  mag-product:
    image: mag-product
    build: product/.
  mag-order:
    image: mag-order
    build: order/.
  mag-auth:
    image: mag-auth
    build: auth/.
  mag-user:
    image: mag-user
    build: user/.