version: "3"
    
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Groupe1!GG
    ports:
      - "5432:5432"
    networks:
      - netservices

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alexis.baudry@viacesi.fr
      PGADMIN_DEFAULT_PASSWORD: Groupe1!GG
    ports:
      - "8081:80"
    networks:
      - netservices

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: Groupe1!GG
    ports:
     - "27017:27017"
    networks:
      - netservices


networks:
  netservices:
    external:
      name: netservices