version: "3.9"
    
services:

  mag_middleware:
    image: mag_middleware
    build: .
    ports:
      - "443:443"
    networks:
      - netservices

networks:
  netservices:
    external:
      name: netservices