apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-auth
  name: mag-auth
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    io.kompose.service: mag-auth
status:
  loadBalancer: {}
