apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-restaurant
  name: mag-restaurant
spec:
  ports:
  - name: "8095"
    port: 8095
    targetPort: 8095
  selector:
    io.kompose.service: mag-restaurant
status:
  loadBalancer: {}
