apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-order
  name: mag-order
spec:
  ports:
  - name: "8094"
    port: 8094
    targetPort: 8094
  selector:
    io.kompose.service: mag-order
status:
  loadBalancer: {}
