apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-product
  name: mag-product
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8093
  selector:
    io.kompose.service: mag-product
status:
  loadBalancer: {}
