apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-user
  name: mag-user
spec:
  ports:
  - name: "8092"
    port: 8092
    targetPort: 8092
  selector:
    io.kompose.service: mag-user
status:
  loadBalancer: {}
