apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mag-auth
  name: mag-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mag-auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/netservices: "true"
        io.kompose.service: mag-auth
    spec:
      containers:
      - image: kallly/mag-auth
        name: mag-auth
        ports:
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
status: {}
